[instagram-rtmps]
client=yes
accept=127.0.0.1:19351
connect=live-upload.instagram.com:443
verifyChain=yes
CAfile=/etc/ssl/certs/ca-certificates.crt
sni=live-upload.instagram.com
checkHost=live-upload.instagram.com
