[kick-rtmps]
client = yes
accept = 127.0.0.1:19356
connect = fa723fc1b171.global-contribute.live-video.net:443
checkHost = fa723fc1b171.global-contribute.live-video.net
sni = fa723fc1b171.global-contribute.live-video.net
