[kick-rtmps]
client=yes
accept=127.0.0.1:19356
connect=fa723fc1b171.global-contribute.live-video.net:443
verifyChain=yes
CAfile=/etc/ssl/certs/ca-certificates.crt
sni=fa723fc1b171.global-contribute.live-video.net
