pid = /var/run/stunnel4/stunnel.pid
output = /dev/stdout
foreground = yes
debug = info

[youtube-live]
client = yes
accept = 127.0.0.1:19355
connect = a.rtmps.youtube.com:443
sni = a.rtmps.youtube.com

[youtube-backup]
client = yes
accept = 127.0.0.1:19357
connect = b.rtmps.youtube.com:443
sni = b.rtmps.youtube.com

[twitch-rtmps]
client = yes
accept = 127.0.0.1:19353
connect = ingest.global-contribute.live-video.net:443
sni = ingest.global-contribute.live-video.net

[kick-rtmps]
client = yes
accept = 127.0.0.1:19356
connect = fa723fc1b171.global-contribute.live-video.net:443
sni = fa723fc1b171.global-contribute.live-video.net

[facebook-rtmps]
client = yes
accept = 127.0.0.1:19350
connect = live-api-s.facebook.com:443
sni = live-api-s.facebook.com

[instagram-rtmps]
client = yes
accept = 127.0.0.1:19351
connect = live-upload.instagram.com:443
sni = live-upload.instagram.com

[tiktok-rtmps]
client = yes
accept = 127.0.0.1:19358
connect = push-rtmp-f5-ap-southeast-1.tiktokcdn.com:443
sni = push-rtmp-f5-ap-southeast-1.tiktokcdn.com

[x-rtmps]
client = yes
accept = 127.0.0.1:19354
connect = va.pscp.tv:443
sni = va.pscp.tv
