[tiktok-rtmps]
client=yes
accept=127.0.0.1:19358
connect=push-rtmp-f5-ap-southeast-1.tiktokcdn.com:443
checkHost = push-rtmp-f5-ap-southeast-1.tiktokcdn.com
sni = push-rtmp-f5-ap-southeast-1.tiktokcdn.com
