[twitch-rtmps]
client = yes
accept = 127.0.0.1:19353
connect = ingest.global-contribute.live-video.net:443
checkHost = ingest.global-contribute.live-video.net
sni = ingest.global-contribute.live-video.net
