[twitch-rtmps]
client=yes
accept=127.0.0.1:19353
connect=ingest.global-contribute.live-video.net:443
sni=ingest.global-contribute.live-video.net
verifyChain = yes
checkHost = ingest.global-contribute.live-video.net
